# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/max/eclipse/cpp-photon/workspace/pbqp-papa

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/max/eclipse/cpp-photon/workspace/pbqp-papa

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/max/eclipse/cpp-photon/workspace/pbqp-papa/CMakeFiles /home/max/eclipse/cpp-photon/workspace/pbqp-papa/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/max/eclipse/cpp-photon/workspace/pbqp-papa/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pbqp_io

# Build rule for target.
pbqp_io: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pbqp_io
.PHONY : pbqp_io

# fast build rule for target.
pbqp_io/fast:
	$(MAKE) -f CMakeFiles/pbqp_io.dir/build.make CMakeFiles/pbqp_io.dir/build
.PHONY : pbqp_io/fast

#=============================================================================
# Target rules for targets named pbqp_solving

# Build rule for target.
pbqp_solving: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pbqp_solving
.PHONY : pbqp_solving

# fast build rule for target.
pbqp_solving/fast:
	$(MAKE) -f CMakeFiles/pbqp_solving.dir/build.make CMakeFiles/pbqp_solving.dir/build
.PHONY : pbqp_solving/fast

#=============================================================================
# Target rules for targets named core_pbqp_representation

# Build rule for target.
core_pbqp_representation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 core_pbqp_representation
.PHONY : core_pbqp_representation

# fast build rule for target.
core_pbqp_representation/fast:
	$(MAKE) -f include/CMakeFiles/core_pbqp_representation.dir/build.make include/CMakeFiles/core_pbqp_representation.dir/build
.PHONY : core_pbqp_representation/fast

#=============================================================================
# Target rules for targets named pbqp-io

# Build rule for target.
pbqp-io: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pbqp-io
.PHONY : pbqp-io

# fast build rule for target.
pbqp-io/fast:
	$(MAKE) -f src/CMakeFiles/pbqp-io.dir/build.make src/CMakeFiles/pbqp-io.dir/build
.PHONY : pbqp-io/fast

#=============================================================================
# Target rules for targets named json

# Build rule for target.
json: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 json
.PHONY : json

# fast build rule for target.
json/fast:
	$(MAKE) -f submodules/CMakeFiles/json.dir/build.make submodules/CMakeFiles/json.dir/build
.PHONY : json/fast

#=============================================================================
# Target rules for targets named degreeZeroReductorTest

# Build rule for target.
degreeZeroReductorTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 degreeZeroReductorTest
.PHONY : degreeZeroReductorTest

# fast build rule for target.
degreeZeroReductorTest/fast:
	$(MAKE) -f test/CMakeFiles/degreeZeroReductorTest.dir/build.make test/CMakeFiles/degreeZeroReductorTest.dir/build
.PHONY : degreeZeroReductorTest/fast

#=============================================================================
# Target rules for targets named matrixTest

# Build rule for target.
matrixTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 matrixTest
.PHONY : matrixTest

# fast build rule for target.
matrixTest/fast:
	$(MAKE) -f test/CMakeFiles/matrixTest.dir/build.make test/CMakeFiles/matrixTest.dir/build
.PHONY : matrixTest/fast

#=============================================================================
# Target rules for targets named bruteForceSolverTest

# Build rule for target.
bruteForceSolverTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bruteForceSolverTest
.PHONY : bruteForceSolverTest

# fast build rule for target.
bruteForceSolverTest/fast:
	$(MAKE) -f test/CMakeFiles/bruteForceSolverTest.dir/build.make test/CMakeFiles/bruteForceSolverTest.dir/build
.PHONY : bruteForceSolverTest/fast

#=============================================================================
# Target rules for targets named graphTests

# Build rule for target.
graphTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphTests
.PHONY : graphTests

# fast build rule for target.
graphTests/fast:
	$(MAKE) -f test/CMakeFiles/graphTests.dir/build.make test/CMakeFiles/graphTests.dir/build
.PHONY : graphTests/fast

#=============================================================================
# Target rules for targets named serializerTests

# Build rule for target.
serializerTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 serializerTests
.PHONY : serializerTests

# fast build rule for target.
serializerTests/fast:
	$(MAKE) -f test/CMakeFiles/serializerTests.dir/build.make test/CMakeFiles/serializerTests.dir/build
.PHONY : serializerTests/fast

#=============================================================================
# Target rules for targets named pbqpSolutionTest

# Build rule for target.
pbqpSolutionTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pbqpSolutionTest
.PHONY : pbqpSolutionTest

# fast build rule for target.
pbqpSolutionTest/fast:
	$(MAKE) -f test/CMakeFiles/pbqpSolutionTest.dir/build.make test/CMakeFiles/pbqpSolutionTest.dir/build
.PHONY : pbqpSolutionTest/fast

#=============================================================================
# Target rules for targets named connectedComponentSeparatorTest

# Build rule for target.
connectedComponentSeparatorTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 connectedComponentSeparatorTest
.PHONY : connectedComponentSeparatorTest

# fast build rule for target.
connectedComponentSeparatorTest/fast:
	$(MAKE) -f test/CMakeFiles/connectedComponentSeparatorTest.dir/build.make test/CMakeFiles/connectedComponentSeparatorTest.dir/build
.PHONY : connectedComponentSeparatorTest/fast

#=============================================================================
# Target rules for targets named degreeTwoReductorTest

# Build rule for target.
degreeTwoReductorTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 degreeTwoReductorTest
.PHONY : degreeTwoReductorTest

# fast build rule for target.
degreeTwoReductorTest/fast:
	$(MAKE) -f test/CMakeFiles/degreeTwoReductorTest.dir/build.make test/CMakeFiles/degreeTwoReductorTest.dir/build
.PHONY : degreeTwoReductorTest/fast

#=============================================================================
# Target rules for targets named degreeOneReductorTest

# Build rule for target.
degreeOneReductorTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 degreeOneReductorTest
.PHONY : degreeOneReductorTest

# fast build rule for target.
degreeOneReductorTest/fast:
	$(MAKE) -f test/CMakeFiles/degreeOneReductorTest.dir/build.make test/CMakeFiles/degreeOneReductorTest.dir/build
.PHONY : degreeOneReductorTest/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... edit_cache"
	@echo "... pbqp_io"
	@echo "... pbqp_solving"
	@echo "... core_pbqp_representation"
	@echo "... pbqp-io"
	@echo "... json"
	@echo "... degreeZeroReductorTest"
	@echo "... matrixTest"
	@echo "... bruteForceSolverTest"
	@echo "... graphTests"
	@echo "... serializerTests"
	@echo "... pbqpSolutionTest"
	@echo "... connectedComponentSeparatorTest"
	@echo "... degreeTwoReductorTest"
	@echo "... degreeOneReductorTest"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

